stages:
    - build
    - test
    
build:
    stage: build
    except:
        - java-syntax
        - DI-manual-no-Gradle
    image: eclipse-temurin:17-alpine
    script: 
        - chmod +x ./gradlew
        - ./gradlew build

test:
    stage: test
    image: eclipse-temurin:17-alpine
    script: 
        - chmod +x ./gradlew
        - ./gradlew test