image: gradle:7.4.2-jdk17
stages:
  - test
  - build
cache:
  paths:
    - .gradle/caches
    - .gradle/wrapper

build:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  only:
    - test
  script:
    - ./gradlew clean test